version: '2'

services:
  envoy:
    build: ./envoy
    ports:
      - '5555:5555'
    links:
      - server
    networks:
      - test

  server:
    ports: ['5001:5001']
    image: my_grpc
    tty: true
    networks:
      - test


networks:
  test:
    driver: bridge
