version: '2'

services:
  envoy:
    image: my_envoy
    ports: ['5555:5555']
    links:
      - my_grpc
    networks:
      - test

  my_grpc:
    ports: ['5001:5001']
    image: my_grpc
    tty: true
    networks:
      - test


networks:
  test:
    driver: bridge
